### ISSUE TITLE
Request to attend TC39 as OpenJS delegate

### ISSUE THREAD

**Issue by DerekNonGeneric** [openjs-foundation/standards#143]
I'd like to attend the July TC39 meeting as a delegate for the OpenJS Foundation as a Node.js Core Collaborator. The meeting is from July 13<sup>th</sup> to July 16<sup>th</sup>. The goal of this attendance is to present a proposal for an `AssertionError`, which I would be championing myself and would be requesting advancement to stage 1. 

Full disclosure I am also affiliated with:
- the AMP Project, which is another OpenJS Foundation project
- Indiana University, which is another Ecma member organization

My attendance was recommended by @bakkot.<sup>[1](#note-1)</sup> This issue was suggested to be opened by @ljharb.<sup>[2](#note-2)</sup>

1. <a id="note-1" name="note-1"></a>Full context available in [`#tc39-general` Matrix channel][]
2. <a id="note-2" name="note-2"></a>Full context available in [`#standards` OpenJSF Slack channel][]

[`#tc39-general` Matrix channel]: https://matrixlogs.bakkot.com/TC39_General/2021-06-05#L1-L23
[`#standards` OpenJSF Slack channel]: https://openjs-foundation.slack.com/archives/CKF0PCF54

**Comment by ljharb** [comment]
Via IU, you’re potentially a delegate already - can they not send you as their delegate?

**Comment by DerekNonGeneric** [comment]
Good question @ljharb, there is currently only one other IU delegate. After looking into it further, he could not find any documentation stating requirements, so that seems like another avenue worth exploring further. Lack of precedent seems to be the problem, but he said he would be getting back to me.

One valid point he made when we spoke was that attending as a Node.js Core Collaborator would hold more weight and recommended pursuing becoming a delegate this way.

**Comment by ljharb** [comment]
There’s no weight afforded by attending as a delegate of anyone in particular, really - it’s more that you could bypass the approval process in the foundation since IU can summarily decide you’re a delegate.

**Comment by DerekNonGeneric** [comment]
> There’s no weight afforded by attending as a delegate of anyone in particular, really [&hellip;]

Hmm, good point. I am a bit unsure what the meaning of &ldquo;weight&rdquo; might have been since I am still in the process of becoming familiar with how TC39 operates. Perhaps in the context of helping justify advancement? Maybe representing the project with an explicit interest in the proposal might have been what was meant. That is just my wild guess, but who knows.

> [&hellip;] bypass the approval process in the foundation [&hellip;]

I don't see why I would want to do that. The current approval process in the foundation is for the standards group to discuss it, which seems perfectly fine to me, seeing as how I would be utilizing the support offered by the foundation either way, and this group is comprised of the people whose input I will be seeking.

Is the next meeting going to be happening in the not-too-distant future? If so, please add this issue to your agenda. Thanks!

/cc @jorydotcom

**Comment by michaelchampion** [comment]
[disclaimer - I've never worked in TC39, I can only speak to what was typical of the various standards organizations I worked in from 1997 - 2020 as a delegate of various companies ranging from a doomed startup to a market-leading multinational]

> There’s no weight afforded by attending as a delegate of anyone in particular

In my experience, that is the stated policy but not the actual reality: my "weight" (apparent influence in a group) changed noticeably when my affiliation changed.  Opinions about standards matters that were tolerated but ignored when I worked for a startup became serious proposals to be accommodated (or argued against) when I worked for an implementer with significant mindshare or market share.  And went back to being ignored when I retired, oh well 😿 

So, I'd suggest leveraging the https://en.wikipedia.org/wiki/Halo_effect : If you want to promote an AssertionError feature, doing so as a delegate from a prominent project such as Node.js would indeed carry more weight than as a delegate from an academic institution.

**Comment by ljharb** [comment]
While i agree with your sentiment, association with the node project would be relevant regardless of how you attend the meeting.

**Comment by obensource** [comment]
Hi @DerekNonGeneric 👋

It’s unfortunate that we don’t have official guidelines published regarding the representation of the OpenJS Foundation at standards bodies yet ([coming soon](https://github.com/openjs-foundation/standards/issues/142), our apologies) –– so for now I will relay the Standards WG’s current position on this:

In order to represent the OpenJS Foundation at an approved standards body (like tc39), some basic criteria need to be met:

1. The delegate / attendee should be active in the Standards WG (for example: actively attending WG meetings and/or weighing in on issues and PRs).

2. The standards body that the OpenJS Foundation will send a representative to has requested representation from the OpenJS Standards Working Group, or a member project’s governing board.

3. This is the only way for an individual to participate at a standards body. If the delegate / attendee has support from another participating member group, they should pursue going through that channel. This is preferred especially in the interest of financially supporting standards bodies, over attending through a Non-profit Foundation (like the OpenJS).

We’d like to thank you sincerely for your interest in this, and even though at present this criteria isn’t met for you in regards to representing the OpenJS Foundation at tc39, I sincerely hope this helps as a guide for any future participation through the OpenJS Standards WG you wish to engage in, and I commend you for your eagerness to both join in and help JS grow. Thanks a million! 🍻

**Comment by DerekNonGeneric** [comment]
Happy to have been able to help you all w/ making progress on defining some criteria here.

I am looking forward to seeing how the more developed statement will result and may be able to help in the near future.

I am currently quite busy w/ working on projects in TC39 itself, so may not be as available as I wish I could be.

**Comment by obensource** [comment]
Thank you so much for your understanding @DerekNonGeneric, it's truly appreciated. Thank you for your contributions and interest! 🙏
