### ISSUE TITLE
Standards WG at OpenJS World 2022

### ISSUE THREAD

**Issue by rginn** [openjs-foundation/standards#168]
Last year, the OpenJS Standards WG outlined six focus areas, where the consensus was to focus on learning in 2021. With OpenJS World returning to an in-person event in June, 2022, should we consider adding another focus from the list? -> “OpenJS Foundation helps make standards bodies nicer places to do work.” 

Initial activities brainstormed included:
- Technical writing mentorship for difficult feedback (let’s re-write that issue)
- IRL (in real life) conference on JS Community standards activities (bring together WHATWG/W3C/Ecma)
- Recognition/award (XKCD 2347)
- Mentorship/office hours for advice, challenging topics

Reposting the 2021 focus area list that we discussed with project leads to help prioritize:

1. OpenJS Foundation is a place to develop standards proposals/workstreams which are being missed by the bigger SDOs – "Fill the Cracks."
2. OpenJS Foundation is a place where the JS Community discusses
3. proposal needs.
4. OpenJS Foundation is a place for discovery of "standard stacks" e.g. we do analysis of our projects to present common pathways/approaches.
5. OpenJS Foundation is a place where projects with standards-related goals receive support for their work, and where folks in those project groups cross-collaborate.
6. OpenJS Foundation is a place where people can learn and begin to onboard into standards development.
7. OpenJS Foundation helps make standards bodies nicer places to do work.

**Comment by michaelchampion** [comment]
Some thoughts, not sure exactly how they fit in:
- It's very important to help W3C, WHATWG, and ECMA work together effectively on issues that touch on all of them but none clearly "own".  The WHATG-W3C Memorandum of Understanding is not working well in practice, perhaps because the workers in both orgs value their own parts more than the union of them.  But OpenJS could be the "voice of the community" (since almost all real websites involve JS code) to keep them focused on adding value for end-users rather than particular sub-communities.

- Editing specs and facilitating collaboration between spec writers and code writers in a way that works for users is HARD, irrespective of political/personality stuff.   If OpenJS can help recruit a new generation of people to do this kind of work ad mentor them how to do it well, that would be a great contribution to the larger community.

- I appreciate the reference to XKCD 2347; lack of recognition for contributions / burnout by people who contribute without financial support or even assistance with the "janitorial" work (https://twitter.com/alecstapp/status/1291732640018632712 ) is getting to be a real problem.

**Comment by rginn** [comment]
Standards were well represented at OpenJS World 2022, including a keynote panel, breakout sessions, and a workshop. Check out the OpenJS YouTube event playlist:  https://www.youtube.com/playlist?list=PLyspMSh4XhLMSpb4yqi0aPxSioNaP1Wkn. 

OpenJS also celebrated its first JavaScriptLandia Community Awards recipients at the conference, including the Pathfinder Award for Standards @TzviyaSiegman. https://openjsf.org/announcement/2022/06/07/first-ever-javascriptlandia-awards-celebrate-community-leaders/

Many thanks to the Standards WG and all those who participated in the event program development, community awards program, and presentations.
