### ISSUE TITLE
2022-2023 Public Calendar for web standards group meetings

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/standards#191]
Per our meeting, we created a public calendar to share meeting dates, conferences, and other important events. See / test calendar [here](https://calendar.google.com/calendar/u/0?cid=Y183bHQ1NWNjc2FtbW8ybXNvZ24zamVvbXR0Z0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

**Comment by jorydotcom** [comment]
Calendar has been updated with TC39 meetings for remainder of 2023, as well as W3C AC, TPAC, and OpenJS World. 
Question to @eemeli - are any of the unicode events applicable? https://unicode.org/timesens/calendar.html

Broader question: other orgs meetings we should include?

**Comment by eemeli** [comment]
I don't think the overlap is too great with the listed Unicode events. If an in-person Unicode Conference does get organised again (on hiatus since 2021) that would be good to note.

The recurring MFWG meetings are currently mostly biweekly on Mondays, but those probably don't need to be tracked in this calendar either.

**Comment by jorydotcom** [comment]
Thanks Eemeli!!
