### ISSUE TITLE
OpenJS réponse to W3C CEO survey

### ISSUE THREAD

**Issue by michaelchampion** [openjs-foundation/standards#219]
https://eu.surveymonkey.com/r/SZQVR6K is open until April 7 to get W3C Advisory Committee  (@jorydotcom is our representative) input to their CEO search committee. There is a question ranking the desirable attributes of a CEO which frankly doesn't seem all that useful, but 3 open ended questions that might be:  competencies the CEO should have, opportunities W3C has that a CEO could help with, and challenges the CEO should be ready to face.

An OpenJS answer might point to the challenges and opportunities at the intersection of open source and open standards, and suggest the new CEO must demonstrate a sophisticated understanding of how the ecosystems work together. Developers leverage open source tools and products to build standards-compliant websites and applications.  Most hands-on web developers interact with the underlying standards through JS-powered front-end frameworks and back-end platforms such as Node.  Nevertheless there is tension and frequent "social media wars" between framework advocates and raw platform format/API advocates that frame this as a competition. W3C staff have a tendency to support the "fundamentalists", partly because few have hands-on experience or social contact with real world web developers.  

Neither extreme -- completely hiding the web platform standards behind JS frameworks or fighting against the frameworks as intrinsically bloated, slow, and general evil -- is good for the OpenJSF or Web communities.  It would not be helpful to have a W3C CEO who  thinks their job is to help the web platform better "compete" with the JS frameworks, or push "declarative" HTML+CSS over JS in general (as Tim Berners-Lee did long ago).

So the issue is:
- Should OpenJS answer the survey along the lines of the argument above?
- What exactly can we say in answers to the 3 questions to convey this argument?

Strawman proposal just to start discussion:

Competencies: CEO candidates should have a general technical understanding of how developers actually build websites, what the platform technologies (HTML, CSS, Web APIs, HTTP and server-side tech) generally do, and why JS frameworks have become a key part of developers toolchains.

Opportunities: Build better relationships with OSS/JS tool and framework developers to understand the platform problems they address in the short run and fix those problems in the core platform over time.

Challenges: CEO should realize the raw W3C standards don't offer a great developer experience. Understand that the standard formats and APIs provide a very powerful platform but one that is complex and overwhelming to developers who just want to put up a website.

**Comment by jorydotcom** [comment]
This is an interesting survey. I hope they get the info the are looking for out of it - perhaps most valuable to the board would be any recommended person(s) they gather from the membership as potential recruits. 

>An OpenJS answer might point to the challenges and opportunities at the intersection of open source and open standards, and suggest the new CEO must demonstrate a sophisticated understanding of how the ecosystems work together. Developers leverage open source tools and products to build standards-compliant websites and applications. Most hands-on web developers interact with the underlying standards through JS-powered front-end frameworks and back-end platforms such as Node. Nevertheless there is tension and frequent "social media wars" between framework advocates and raw platform format/API advocates that frame this as a competition. W3C staff have a tendency to support the "fundamentalists", partly because few have hands-on experience or social contact with real world web developers.

I agree with this very much, and think it's likely very very crucial for the W3C's survival. We need to respond to this survey today, so I will take Mike's comments as the jumping off point and post proposed responses in our slack channel.

**Comment by LeaVerou** [comment]
Coming a bit late to this. Most of this is great, thank you for starting this @michaelchampion!
Some thoughts and questions:

> or push "declarative" HTML+CSS over JS in general (as Tim Berners-Lee did long ago)

As someone who generally thinks making declarative languages like HTML/CSS more powerful is a _great_ thing for the DX and learnability of the web platform (not over JS though, I think that's a false dichotomy — they work in unison), I would love some background on this. What did TimBL do long ago?

> Challenges: CEO should realize the raw W3C standards don't offer a great developer experience. Understand that the standard formats and APIs provide a very powerful platform but one that is complex and overwhelming to developers who just want to put up a website.

As phrased, I'm not sure what the challenge here is exactly. 
What should they _do_ once they realize this?
Should they just resign to this fact and accept that having great DX is simply out of scope? Or (hopefully) should they push towards a direction of improving the DX of W3C standards?
But then… isn't the primary benefit of frameworks that they offer improved DX over the raw standards?
What is the difference between developing W3C standards with great DX and competing with frameworks?

**Comment by michaelchampion** [comment]
The response was due last week, and Jory wisely edited out some of the stuff you disagree with, so we can probably close the issue 😉

But the larger question how W3C could better work with the OSS / dev framework community is worth discussing longer term. 

Personally, and speaking from pretty much a five year out of date perspective,  I think W3C should be more attuned to the DX of the raw standards, and treat the framework s more as hints of what does work for the devs and learn from rather than fight them.

**Comment by LeaVerou** [comment]
I'm aware the survey was due last week (hence my coming late to this remark), though I hadn't realized these parts were edited out when I looked at the responses in Slack.

> But the larger question how W3C could better work with the OSS / dev framework community is worth discussing longer term.

That's exactly the discussion I was trying to start, and that does not have the same short time constraints as the survey :)

> Personally, and speaking from pretty much a five year out of date perspective, I think W3C should be more attuned to the DX of the raw standards, and treat the framework s more as hints of what does work for the devs and learn from rather than fight them.

Agreed, I think tools and frameworks are *excellent* for exploring a) developer needs and b) as rapid prototyping to find out what works and what doesn't. 

Even when we can't or shouldn't adopt something similar in the web platform, they are excellent for signaling what problems developers are facing, which is input most API designers really crave. 

Example: CSS-in-JS tools. I think it would have been a mistake to simply implement something like this in the web platform, since the reason these tools were designed the way they were was due to the lack of underlying web platform concepts to support what they were trying to do. However, the proliferation of these libraries indicates certain problems that developers are having that absolutely *should* be addressed at the standards level. Some of these problems are being worked on in the CSS WG and others via the Web Components specs (my intuition is we have not yet identified standards-based solutions for all of these problems).

As another example, many (most?) client-side frameworks seem to primarily center around encapsulation (with components), reactivity, and routing. All three are so fundamental in building web applications that IMO *should* be addressed by the underlying platform, yet only components are, and not with the same use cases in mind. But we only realized this a decade after these frameworks started coming out. By the time there are Web Platform APIs for these concepts, there will be new fundamental concepts that only frameworks are addressing, since third-party tools can iterate much faster, and there is a lower barrier to entry.

**Comment by jorydotcom** [comment]
Per yesterday's call, we are taking this off the agenda and closing this issue. However we want to capture the ideas and examples from @LeaVerou and @michaelchampion here in a new issue to continue the conversation about bringing this feedback to the W3C.
